name: ms_range
description: A powerfull lib to creante ranges and compare if number is in range
version: 0.2.0
homepage: https://github.com/Marcus-Software/ms_range

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.9.2